name: school_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17

  # Databases
  cloud_firestore: ^3.1.17
  sqflite: ^2.0.2+1
  sqlbrite: ^2.2.0

  # Background notification worker
  workmanager: ^0.5.0
  flutter_local_notifications: ^9.6.0

  # Filesystem
  path: ^1.8.1
  path_provider: ^2.0.11

  # Util
  email_validator: ^2.0.1
  flutter_colorpicker: ^1.0.3
  lit_relative_date_time: ^1.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  perfect_freehand: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
